# Generated by Django 3.2.23 on 2023-11-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ManyToManyField(to='bibli.Editorial'),
        ),
    ]
